import React, { useState } from 'react'
import styles from './Learn.module.css'

const Learn = () => {
  // state to track which topic is currently selected
  const [selectedTopic, setSelectedTopic] = useState('identity')

  const topics = {
    identity: {
      title: 'Safe Online Identity & Password Hygiene',
      subtitle:
        'Building Your Digital Fortress: Protecting Your Online Identity',
      image:
        'https://images.unsplash.com/photo-1563013544-824ae1b704d3?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      content: {
        introduction: `In today's interconnected digital world, your online identity is as valuable as your physical one. Every day, millions of people fall victim to identity theft, data breaches, and cyber attacks that could have been prevented with proper password hygiene and identity protection practices. This comprehensive guide will walk you through the essential strategies to safeguard your digital presence and maintain robust online security.`,

        sections: [
          {
            heading: 'The Foundation: Strong Password Creation',
            content: `Creating strong passwords is your first line of defense against cyber threats. A robust password should be at least 12 characters long and include a combination of uppercase letters, lowercase letters, numbers, and special characters. Avoid using dictionary words, personal information, or predictable patterns like "123456" or "password123".

            Consider using the passphrase method: combine unrelated words with numbers and symbols. For example, "Coffee#Mountain92$Dance" is both memorable and secure. The key is creating something unique that only you would think of, making it nearly impossible for attackers to guess through brute force attacks.`,
          },
          {
            heading: 'Password Uniqueness: Your Digital Keys',
            content: `Using the same password across multiple accounts is like using the same key for your house, car, and office – if someone gets hold of it, they have access to everything. Each online account should have its own unique password. This practice, known as password isolation, ensures that if one account is compromised, your other accounts remain secure.

            The average person has over 80 online accounts, making manual password management nearly impossible. This is where password managers become invaluable tools in your cybersecurity arsenal.`,
          },
          {
            heading: 'Password Managers: Your Digital Vault',
            content: `Password managers are specialized software applications that generate, store, and automatically fill in complex passwords for your various online accounts. Popular options include LastPass, 1Password, Bitwarden, and Dashlane. These tools use advanced encryption to protect your password vault, requiring only one master password to access all your credentials.

            Beyond password storage, modern password managers offer additional features like secure note storage, credit card information management, and even dark web monitoring to alert you if your credentials appear in data breaches.`,
          },
          {
            heading: 'Two-Factor Authentication: Double Your Security',
            content: `Two-factor authentication (2FA) adds an extra layer of security by requiring two forms of identification before granting access to your account. Even if someone obtains your password, they still need the second factor – typically a code sent to your phone, generated by an authenticator app, or provided by a hardware token.

            Enable 2FA on all critical accounts, especially email, banking, social media, and cloud storage services. Authenticator apps like Google Authenticator, Authy, or Microsoft Authenticator are more secure than SMS-based 2FA, as they're not vulnerable to SIM swapping attacks.`,
          },
          {
            heading: 'Social Media Privacy: Controlling Your Digital Footprint',
            content: `Social media platforms are goldmines of personal information for cybercriminals. Review your privacy settings regularly and limit the personal information visible to the public. Avoid posting location data, personal schedules, or sensitive information that could be used for social engineering attacks.

            Be cautious about friend requests from unknown individuals and think twice before clicking on links shared by others. Cybercriminals often create fake profiles to gather information or spread malware through social networks.`,
          },
        ],

        conclusion: `Maintaining good password hygiene and protecting your online identity requires ongoing vigilance and the right tools. By implementing strong, unique passwords, using a reputable password manager, enabling two-factor authentication, and being mindful of your social media presence, you create multiple layers of defense against cyber threats. Remember, cybersecurity is not a destination but a journey – stay informed about new threats and continuously update your security practices.`,
      },
    },

    browsing: {
      title: 'Safe Browsing & Device Practices',
      subtitle:
        'Navigating the Digital World Safely: Essential Browsing and Device Security',
      image:
        'https://images.unsplash.com/photo-1555949963-aa79dcee981c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      content: {
        introduction: `The internet is a powerful tool that has revolutionized how we work, communicate, and access information. However, this digital landscape is also fraught with risks including malware, phishing attacks, data breaches, and privacy violations. Safe browsing practices and proper device security are essential skills in our digital age. This guide provides comprehensive strategies to help you navigate the online world securely while protecting your devices and personal information.`,

        sections: [
          {
            heading: 'Keep Your Digital Arsenal Updated',
            content: `Software updates are your first line of defense against cyber threats. Operating systems, web browsers, and applications regularly release security patches that fix vulnerabilities discovered by security researchers. Cybercriminals actively exploit these known vulnerabilities, making timely updates crucial for your security.

            Enable automatic updates whenever possible for your operating system, antivirus software, and critical applications. For browsers like Chrome, Firefox, or Safari, ensure you're running the latest version and keep extensions updated as well. Set aside time monthly to check for updates on software that doesn't update automatically.`,
          },
          {
            heading: 'The Art of Suspicious Link Detection',
            content: `Malicious links are among the most common attack vectors used by cybercriminals. Before clicking any link, hover over it to preview the destination URL. Be wary of shortened URLs (bit.ly, tinyurl) unless you trust the source completely. Look for telltale signs of phishing: urgent language, spelling errors, mismatched domains, or requests for sensitive information.

            When in doubt, navigate to the website directly by typing the URL into your browser rather than clicking the link. This simple practice can save you from falling victim to phishing scams and malware infections.`,
          },
          {
            heading: 'Download Safety: Choosing Trusted Sources',
            content: `Only download software and files from official websites or verified app stores. Third-party download sites often bundle legitimate software with malware or adware. When downloading files, scan them with your antivirus software before opening, even if they come from trusted sources.

            Be particularly cautious with email attachments, especially from unknown senders. Common malware distribution methods include fake invoice attachments, "urgent" documents, and files with double extensions like "report.pdf.exe". When receiving unexpected attachments, verify with the sender through a separate communication channel before opening.`,
          },
          {
            heading: 'Antivirus and Anti-Malware Protection',
            content: `Modern antivirus solutions provide real-time protection against viruses, malware, ransomware, and other threats. Choose reputable antivirus software from established companies like Norton, McAfee, Kaspersky, or Bitdefender. Many operating systems now include built-in protection (Windows Defender, macOS XProtect) that provides adequate security for most users.

            Configure your antivirus to run regular full system scans and keep real-time protection enabled. Consider supplementing with specialized anti-malware tools like Malwarebytes for additional protection against advanced threats that traditional antivirus might miss.`,
          },
          {
            heading: 'Public Wi-Fi: The Digital Wild West',
            content: `Public Wi-Fi networks in cafes, airports, and hotels are convenient but inherently insecure. These networks often lack proper encryption, making it easy for cybercriminals to intercept your data. Avoid accessing sensitive information like banking websites, email, or work documents while connected to public Wi-Fi.

            If you must use public Wi-Fi for sensitive activities, consider using a Virtual Private Network (VPN) to encrypt your internet traffic. VPN services like NordVPN, ExpressVPN, or CyberGhost create a secure tunnel between your device and the internet, protecting your data from prying eyes.`,
          },
          {
            heading: 'Data Backup: Your Safety Net',
            content: `Regular data backups are essential for protecting against ransomware, hardware failure, and accidental deletion. Follow the 3-2-1 backup rule: maintain three copies of important data, store them on two different types of media, and keep one copy offsite or in the cloud.

            Cloud storage services like Google Drive, Dropbox, or iCloud offer convenient automatic backup solutions. For additional security, consider using external hard drives for local backups. Test your backups regularly to ensure they're working properly and that you can restore your data when needed.`,
          },
        ],

        conclusion: `Safe browsing and device security practices are fundamental skills in our digital world. By keeping your software updated, being cautious with links and downloads, using reputable security software, avoiding risky public Wi-Fi activities, and maintaining regular backups, you significantly reduce your exposure to cyber threats. Remember that cybersecurity is an ongoing process – stay informed about new threats, regularly review your security practices, and maintain a healthy skepticism when interacting with unfamiliar online content. Your digital safety depends on the habits you build today.`,
      },
    },
  }

  return (
    <div className={styles.learn}>
      <div className={styles.container}>
        {/* page header */}
        <header className={styles.header}>
          <h1 className={styles.title}>Learning Center</h1>
          <p className={styles.subtitle}>
            Master essential concepts through comprehensive &<br></br>
            practical guides!
          </p>
        </header>

        {/* topic selection buttons - updating state on click */}
        <nav className={styles.topicSelector}>
          <button
            className={`${styles.topicBtn} ${
              selectedTopic === 'identity' ? styles.active : ''
            }`}
            onClick={() => setSelectedTopic('identity')} // sets state to identity
          >
            <span className={styles.topicIcon}></span>
            Safe Online Identity
          </button>
          <button
            className={`${styles.topicBtn} ${
              selectedTopic === 'browsing' ? styles.active : ''
            }`}
            onClick={() => setSelectedTopic('browsing')} // sets state to browsing
          >
            <span className={styles.topicIcon}></span>
            Safe Browsing
          </button>
        </nav>

        {/* main content area */}
        <article className={styles.content}>
          <div className={styles.topicCard}>
            <div className={styles.articleHeader}>
              <img
                src={topics[selectedTopic].image} // dynamic image based on selected topic
                alt={topics[selectedTopic].title}
                className={styles.heroImage}
              />
              <div className={styles.headerContent}>
                <h2 className={styles.topicTitle}>
                  {topics[selectedTopic].title}
                </h2>
                <p className={styles.topicSubtitle}>
                  {topics[selectedTopic].subtitle}
                </p>
              </div>
            </div>

            <div className={styles.articleBody}>
              {/* introduction section */}
              <div className={styles.introduction}>
                <p>{topics[selectedTopic].content.introduction}</p>
              </div>

              {/* render all sections dynamically */}
              <div className={styles.sections}>
                {topics[selectedTopic].content.sections.map(
                  (section, index) => (
                    <section key={index} className={styles.section}>
                      <h3 className={styles.sectionHeading}>
                        {section.heading}
                      </h3>
                      <div className={styles.sectionContent}>
                        {section.content
                          .split('\n\n') // split into paragraphs
                          .map((paragraph, pIndex) => (
                            <p key={pIndex}>{paragraph.trim()}</p>
                          ))}
                      </div>
                    </section>
                  )
                )}
              </div>

              {/* conclusion / key takeaways */}
              <div className={styles.conclusion}>
                <h3 className={styles.conclusionHeading}>Key Takeaways</h3>
                <p>{topics[selectedTopic].content.conclusion}</p>
              </div>
            </div>
          </div>
        </article>
      </div>
    </div>
  )
}

export default Learn